[33mWARNING [0m urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107094e60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/dec24f2dcc3fbfe3cd9c877dbf32b6dd/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107095b50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/dec24f2dcc3fbfe3cd9c877dbf32b6dd/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107096ea0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/dec24f2dcc3fbfe3cd9c877dbf32b6dd/element