{"name": "test_registration_form", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Sign up successful' in 'This user already exist.'\n +  where 'This user already exist.' = <selenium.webdriver.common.alert.Alert object at 0x10667bec0>.text", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"6b31d999d897383abf19daccd499b30b\")>\n\n    def test_registration_form(driver):\n        wait = WebDriverWait(driver, 10)\n        driver.find_element(By.ID, \"signin2\").click()\n        wait.until(EC.element_to_be_clickable((By.ID, \"sign-username\"))).send_keys(\"TestYura123\")\n        driver.find_element(By.ID, \"sign-password\").send_keys(\"Test12345\")\n        driver.find_element(By.XPATH, \"//button[text()='Sign up']\").click()\n        alert = wait.until(EC.alert_is_present())\n>       assert \"Sign up successful\" in alert.text\nE       AssertionError: assert 'Sign up successful' in 'This user already exist.'\nE        +  where 'This user already exist.' = <selenium.webdriver.common.alert.Alert object at 0x10667bec0>.text\n\ntests/test_authorization_and_registration.py:37: AssertionError"}, "start": 1739231223642, "stop": 1739231225146, "uuid": "023a437d-56e2-4221-b0d7-bbd469dee699", "historyId": "17c54c8943785dc49fe70debee7e01f3", "testCaseId": "17c54c8943785dc49fe70debee7e01f3", "fullName": "tests.test_authorization_and_registration#test_registration_form", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorization_and_registration"}, {"name": "host", "value": "MacBook-Pro-Natasha.local"}, {"name": "thread", "value": "91139-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorization_and_registration"}]}