{"name": "test_site_functionality[edge]", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service /Users/yurakorneev/.cache/selenium/msedgedriver/mac64/133.0.3065.92/msedgedriver", "trace": "browser = 'edge'\n\n    @pytest.mark.parametrize('browser', ['chrome', 'firefox', 'safari', 'edge'])\n    def test_site_functionality(browser):\n>       driver = get_driver(browser)\n\ntests/test_cross_browser.py:20: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntests/test_cross_browser.py:16: in get_driver\n    return webdriver.Edge(options=options)\n.venv/lib/python3.12/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n.venv/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py:55: in __init__\n    self.service.start()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.edge.service.Service object at 0x10d4dccb0>\n\n    def start(self) -> None:\n        \"\"\"Starts the Service.\n    \n        :Exceptions:\n         - WebDriverException : Raised either when it can't start the service\n           or when it can't connect to the service\n        \"\"\"\n        if self._path is None:\n            raise WebDriverException(\"Service path cannot be None.\")\n        self._start_process(self._path)\n    \n        count = 0\n        while True:\n            self.assert_process_still_running()\n            if self.is_connectable():\n                break\n            # sleep increasing: 0.01, 0.06, 0.11, 0.16, 0.21, 0.26, 0.31, 0.36, 0.41, 0.46, 0.5\n            sleep(min(0.01 + 0.05 * count, 0.5))\n            count += 1\n            if count == 70:\n>               raise WebDriverException(f\"Can not connect to the Service {self._path}\")\nE               selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service /Users/yurakorneev/.cache/selenium/msedgedriver/mac64/133.0.3065.92/msedgedriver\n\n.venv/lib/python3.12/site-packages/selenium/webdriver/common/service.py:120: WebDriverException"}, "parameters": [{"name": "browser", "value": "'edge'"}], "start": 1741033021420, "stop": 1741033069214, "uuid": "83eff88e-160c-4908-a365-217e91131c10", "historyId": "4a094fe4beff59c6b48fa8194a259b45", "testCaseId": "e363eb144849e548050aadff90a6dafb", "fullName": "tests.test_cross_browser#test_site_functionality", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_cross_browser"}, {"name": "host", "value": "MacBook-Pro-Natasha.local"}, {"name": "thread", "value": "25107-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cross_browser"}]}