{"uuid": "0d84562d-8805-4e21-ab94-45eadb0e58f0", "children": ["f7f660f5-fc8d-4d0a-908e-3e40ee7148b5", "82968c97-7640-4c23-8975-fb3f4991bece", "b34baaf3-e8d5-4073-a244-648515bbda84"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/yurakorneev/Documents/shop_project/tests/test_content.py\", line 8, in driver\n    driver = webdriver.Chrome()\n             ^^^^^^^^^^^^^^^^^^\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py\", line 69, in __init__\n    super().__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py\", line 89, in __init__\n    self.service.start()\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/selenium/webdriver/common/service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1739220149279, "stop": 1739220149285}], "start": 1739220149279, "stop": 1739220149448}