{"uuid": "16e4eaea-2cea-4af5-85d3-d1f176d0f317", "children": ["faa9f6a1-6cf3-474e-8fcb-7c6877f1509e", "88f71dd4-6167-424b-8e22-cf2588d140b2"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/yurakorneev/Documents/shop_project/tests/test_perfomance.py\", line 8, in driver\n    driver = webdriver.Chrome()\n             ^^^^^^^^^^^^^^^^^^\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py\", line 69, in __init__\n    super().__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py\", line 89, in __init__\n    self.service.start()\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/selenium/webdriver/common/service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1739220149663, "stop": 1739220149669}], "start": 1739220149663, "stop": 1739220149774}