{"uuid": "fb2038f4-c2e7-427c-8cee-b137ef5173e7", "children": ["7bb14b06-55ff-4555-a68e-a415bd03cde6", "cd5776aa-e484-4687-a121-354d33433d92", "7830390c-8b24-4389-bbf2-39389231d0a5", "c248add3-02d3-49f6-a7d2-637c3a9a6dec", "d4cb3b78-0f7f-4dce-996e-ed253aaa4a0d", "44a8e720-3f4d-4b13-9618-483a9cd3fad1", "c1754353-2162-48d5-b29c-9e018bda94e8", "76ed3cdf-07c2-4a2c-83f1-e1d89e494529", "8fe351c5-3de8-4fc3-b934-27abf681d483", "68c5bb02-0446-45c9-b098-3daf2b0840f3", "0d4798eb-fe4c-4bfd-9e6d-733641fbf40a", "8bf94f91-c379-4f6d-a78b-222ac42fbe4e"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/yurakorneev/Documents/shop_project/tests/test_add_items_to_cart_and_order_placement.py\", line 8, in driver\n    driver = webdriver.Chrome()\n             ^^^^^^^^^^^^^^^^^^\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py\", line 69, in __init__\n    super().__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py\", line 89, in __init__\n    self.service.start()\n  File \"/Users/yurakorneev/Documents/shop_project/.venv/lib/python3.12/site-packages/selenium/webdriver/common/service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1739220147507, "stop": 1739220147512}], "start": 1739220147507, "stop": 1739220148260}